export interface scanSettingsObject {
  meter: meter;
  firstMeter: meterStrict;
}

export interface scannedLineObject {
  status: string;
  statusMessage: string;
  meter: meterStrict;
  line: string;
  output: outputObject[];

  //these items are generated by getter functions
  //and are mostly included in the interface to keep the code organised.
  flat: string[];
  solutions: string[];
  numberOfSolutions: number;
}

export interface outputObject {
  raw: string;
  full: string[];
  error: string;
}

export interface analysedLine {
  scans: [Record<number, quantity>, number[]][];
  error: string;
}

export type scanStatus = "Warning";

export type scanNature = "Full Scan" | "Quantities" | "Input";

export type meter = "Hexameter" | "Pentameter" | "Elegaic"; //only useable meters included.
export type meterStrict = "Hexameter" | "Pentameter";
export type quantity = "Undefined" | "Long" | "Short" | "Break";
export type quantityStrict = "Long" | "Short";

export type vowel =
  | "a"
  | "e"
  | "i"
  | "o"
  | "u"
  | "y"
  | "A"
  | "E"
  | "I"
  | "O"
  | "U"
  | "Y";
